#!/bin/sh

# source common functions; exit if missing
if [[ -f ${UKWACOMMONDIR}/common.sh ]]; then source ${UKWACOMMONDIR}/common.sh; else echo "ERROR: ${UKWACOMMONDIR}/common.sh missing"; exit 1; fi

# globals -----
NOPREFIX=1
DEBUG=

SERVICE='prometheus-node-exporter'


# script ----------
# if node_exporter not already active, enable and start (make active)
_status=$(systemctl is-active ${SERVICE}.service)
if [[ ${_status} != 'active' ]]; then
	log INFO "Enabling and starting ${SERVICE}"
	sudo systemctl daemon-reload
	sudo systemctl enable ${SERVICE}
	sudo systemctl start ${SERVICE}
fi

# show node_exporter status
systemctl status ${SERVICE}

log_stop
